Presentacion/Controllers/ReporteController.cs
using Entidades;
using LogicaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        BLVeh_Ser BLVS = new BLVeh_Ser();
        public ActionResult Inicio()
        {
            return View();
        }

        public ActionResult ListarReporte() {
            return View(BLVS.ObtenerTodo());
        }

        public ActionResult InsertarServicios() {
            List<Vehiculo> listV = new List<Vehiculo>();
            List<Servicios> listS = new List<Servicios>();
            BLServicio BLS = new BLServicio();
            BLVehiculo BLV = new BLVehiculo();
            listV = BLV.ObtenerTodo();
            listS = BLS.ObtenerTodo();
            ViewBag.listadoV = listV;
            ViewBag.listadoS = listS;
            return View();
        }

        public ActionResult AgregarDatos(int cboVehiculo, int cboServicio) {
            Vehiculo_Servicio vs = new Vehiculo_Servicio();

            vs.ID_Servicio = cboServicio;
            vs.ID_Vehiculo = cboVehiculo;
            string msj = BLVS.Agregar(vs);
            string content = "";
            if (msj.Equals("Datos agregados correctamente."))
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Reporte/ListarReporte'; </script>'";
            }
            else
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Reporte/InsertarServicios'; </script>'";
            }
            return Content(content);
        }
    }
}

Presentacion/Views/Reporte/InsertarServicios.cshtml
@model Entidades.Vehiculo_Servicio

@{
    ViewBag.Title = "InsertarServicios";
    Layout = "~/Views/layout/layoutMenu.cshtml";

    var listaVehiculos = ViewBag.listadoV;
    var listaServicios = ViewBag.listadoS;
}

<h2>InsertarServicios</h2>

<div>
    @using (Html.BeginForm("AgregarDatos", "Reporte", FormMethod.Post)) {
    <div>
        <label>Vehículo:</label>
        <select name="cboVehiculo">
            <option value="0">Seleccione un vehículo</option>
            @foreach (var item in listaVehiculos)
            {
                <option value="@item.ID_Vehiculo">@item.Placa</option>
            }
        </select>
    </div>

    <div>
        <label>Servicio:</label>
        <select name="cboServicio">
            <option value="0">Seleccione un servicio</option>
            @foreach (var item in listaServicios)
            {
                <option value="@item.ID_Servicio">@item.Descripcion</option>
            }
        </select>
    </div>
    <div>
        <button type="submit">Agregar</button>
    </div>
    }
    

</div>

Presentacion/Views/Reporte/ListarReporte.cshtml
@model List<Entidades.Vehiculo_Servicio>

@{
    ViewBag.Title = "ListarReporte";
    Layout = "~/Views/layout/layoutMenu.cshtml";
}

<h2>Reporte de servicios asociados a vehículos</h2>

<table border="1">
    <tr>
        <th>Consecutivo</th>
        <th>ID Servicio</th>
        <th>Descripción</th>
        <th>Placa</th>
        <th>Dueño</th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.ID_Vehiculo_Servicio</td>
    <td>@item.Servicios.ID_Servicio</td>
    <td>@item.Servicios.Descripcion</td>
    <td>@item.Vehiculo.Placa</td>
    <td>@item.Vehiculo.Dueno</td>
</tr>
    }
</table>