Presentacion/Controllers/VehiculoController.cs
using LogicaNegocio;
using Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class VehiculoController : Controller
    {
        // GET: Vehiculo

        BLVehiculo BLV = new BLVehiculo();
        public ActionResult Inicio()
        {
            return View();
        }

        public ActionResult ListaVehiculos() {
            return View(BLV.ObtenerTodo());
        }

        public ActionResult AgregarVehiculo() {
            return View();
        }

        public ActionResult InsertarVehiculo(string txtplaca, string txtdueno, string txtmarca) {
            Vehiculo vehiculo = new Vehiculo();
            string msj = "";
            if (txtplaca.Equals(""))
            {
                msj = "Debe ingresar una placa";
            }
            else if (txtdueno.Equals(""))
            {
                msj = "Debe ingresar el nombre del dueño";
            }
            else if (txtmarca.Equals(""))
            {
                msj = "Debe indicar la marca del vehículo";
            }
            else {
                vehiculo.Placa = txtplaca;
                vehiculo.Dueno = txtdueno;
                vehiculo.Marca = txtmarca;
                msj = BLV.Agregar(vehiculo);
            }
            String content = "";
            if (msj.Equals("Vehículo agregado correctamente."))
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Vehiculo/ListaVehiculos'; </script>'";
            }
            else {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Vehiculo/AgregarVehiculo'; </script>'";
            }
            return Content(content);
        }


        public ActionResult ModificarVehiculo(int codigo) {
            return View(BLV.Obtener(codigo));
        }

        public ActionResult ActualizarVehiculo(string txtID, string txtplaca, string txtdueno, string txtmarca) {
            Vehiculo vehiculo = new Vehiculo();
            string msj = "";
            if (txtplaca.Equals(""))
            {
                msj = "Debe ingresar una placa";
            }
            else if (txtdueno.Equals(""))
            {
                msj = "Debe ingresar el nombre del dueño";
            }
            else if (txtmarca.Equals(""))
            {
                msj = "Debe indicar la marca del vehículo";
            }
            else
            {
                vehiculo.Placa = txtplaca;
                vehiculo.Dueno = txtdueno;
                vehiculo.Marca = txtmarca;
                msj = BLV.Modificar(vehiculo, vehiculo.ID_Vehiculo);
            }
            string content = "";
            if (msj.Equals("Datos de vehículo modificados correctamente."))
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('Tarea Existosa'); window.location.href='/Vehiculo/ListaVehiculos'; </script>'";
            }
            else
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('Error, Vehiculo no modificado'); window.location.href='/Vehiculo/ModificarVehiculo'; </script>'";
            }
            return Content(content);
        }

        public ActionResult EliminarVehiculo(int codigo) {
            string msj = BLV.Eliminar(codigo);
            string content = "";
            if (msj.Equals("Los datos del vehículo, se eliminaron correctamente."))
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Vehiculo/ListaVehiculos'; </script>'";
            }
            else
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Vehiculo/ListaVehiculos'; </script>'";
            }
            return Content(content);
        }
    }
}

Presentacion/Views/Vehiculo/AgregarVehiculo.cshtml
@model Entidades.Vehiculo

@{
    ViewBag.Title = "AgregarVehiculo";
    Layout = "~/Views/layout/layoutMenu.cshtml";
}

<h2>Agregar Vehiculo</h2>

<div>
    @using (Html.BeginForm("InsertarVehiculo", "Vehiculo", FormMethod.Post)) {
    <div>
        <div>
            <label for="placa">Placa:</label>
            <input type="text" name="txtplaca" />
        </div>
        <div>
            <label for="dueno">Dueño:</label>
            <input type="text" name="txtdueno" />
        </div>
        <div>
            <label for="marca">Marca:</label>
            <input type="text" name="txtmarca" />
        </div>
        <div>
            <button type="submit">Agregar</button>
        </div>
    </div>
    }
</div>

Presentacion/Views/Vehiculo/ListaVehiculos.cshtml
@model List<Entidades.Vehiculo>

@{
    ViewBag.Title = "ListaVehiculos";
    Layout = "~/Views/layout/layoutMenu.cshtml";
}

<h2>Lista Vehiculos</h2>

<table border="1">
    <tr>
        <th>ID Vehículo</th>
        <th>Placa</th>
        <th>Dueño</th>
        <th>Marca</th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.ID_Vehiculo</td>
    <td>@item.Placa</td>
    <td>@item.Dueno</td>
    <td>@item.Marca</td>
    <td>@Html.ActionLink("Actualizar", "ModificarVehiculo", new { codigo = item.ID_Vehiculo })</td>
    <td>@Html.ActionLink("Eliminar", "EliminarVehiculo", new { codigo = item.ID_Vehiculo })</td>
</tr>
    }
</table>

Presentacion/Views/Vehiculo/ModificarVehiculo.cshtml
@model Entidades.Vehiculo

@{
    ViewBag.Title = "ModificarVehiculo";
    Layout = "~/Views/layout/layoutMenu.cshtml";
}

<h2>Modificar Vehiculo</h2>

<div>
    @using (Html.BeginForm("ActualizarVehiculo", "Vehiculo", FormMethod.Post))
    {
    <div>
        <div>
            <label for="Id">ID Vehículo:</label>
            <input type="text" name="txtID" value="@Model.ID_Vehiculo" readonly/>
        </div>
        <div>
            <label for="placa">Placa:</label>
            <input type="text" name="txtplaca" value="@Model.Placa"/>
        </div>
        <div>
            <label for="dueno">Dueño:</label>
            <input type="text" name="txtdueno" value="@Model.Dueno"/>
        </div>
        <div>
            <label for="marca">Marca:</label>
            <input type="text" name="txtmarca" value="@Model.Marca"/>
        </div>
        <div>
            <button type="submit">Actualizar</button>
        </div>
    </div>
    }
</div>