Presentacion/Controllers/ServicioController.cs
using Entidades;
using LogicaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class ServicioController : Controller
    {
        // GET: Servicio
        BLServicio BLS = new BLServicio();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListaServicios()
        {
            return View(BLS.ObtenerTodo());
        }

        public ActionResult AgregarServicio()
        {
            return View();
        }

        public ActionResult InsertarServicio(string txtdescripcion, string txtmonto) {
            Servicios servicio = new Servicios();
            string msj = "";
            if (txtdescripcion.Equals(""))
            {
                msj = "Debe ingresar una descripción";
            }
            else if (txtmonto.Equals(""))
            {
                msj = "Debe ingresar un monto";
            }
            else {
                servicio.Descripcion = txtdescripcion;
                servicio.Monto = Convert.ToInt32(txtmonto);
                msj = BLS.Agregar(servicio);
            }
            string content = "";
            if (msj.Equals("Servicio agregado correctamente."))
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Servicio/ListaServicios'; </script>'";
            }
            else
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Servicio/AgregarServicio'; </script>'";
            }
            return Content(content);
        }

        public ActionResult ModificarServicio(int codigo) {
            return View(BLS.Obtener(codigo));
        }

        public ActionResult ActualizarServicio(string txtID, string txtdescripcion, string txtmonto) {
            Servicios servicio = new Servicios();
            servicio.ID_Servicio = Convert.ToInt32(txtID);
            servicio.Descripcion = txtdescripcion;
            servicio.Monto = Convert.ToInt32(txtmonto);
            string msj = BLS.Modificar(servicio, servicio.ID_Servicio);
            string content = "";

            if (msj.Equals("Datos de servicio modificados correctamente."))
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Servicio/ListaServicios'; </script>'";
            }
            else
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Servicio/ModificarServicio'; </script>'";
            }
            return Content(content);
        }

        public ActionResult EliminarServicio(int codigo) {
            string msj = BLS.Eliminar(codigo);
            string content = "";

            if (msj.Equals("Los datos del servicio, se eliminaron correctamente."))
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Servicio/ListaServicios'; </script>'";
            }
            else
            {
                content = "<script languaje='javascript' type='text/javascript'> alert('"+msj+"'); window.location.href='/Servicio/ListaServicios'; </script>'";
            }
            return Content(content);
        }
    }
}

Presentacion/Views/Servicio/AgregarServicio.cshtml
@model Entidades.Servicios

@{
    ViewBag.Title = "AgregarServicio";
    Layout = "~/Views/layout/layoutMenu.cshtml";
}

<h2>Agregar Servicio</h2>

<div>
    @using (Html.BeginForm("InsertarServicio", "Servicio", FormMethod.Post))
    {
        <div>
            
            <div>
                <label for="descripcion">Descripción:</label>
                <input type="text" name="txtdescripcion" />
            </div>
            <div>
                <label for="monto">Monto:</label>
                <input type="text" name="txtmonto" />
            </div>
            <div>
                <button type="submit">Agregar</button>
            </div>
        </div>
    }
</div>

Presentacion/Views/Servicio/ListaServicios.cshtml
@model List<Entidades.Servicios>

@{
    ViewBag.Title = "ListaServicios";
    Layout = "~/Views/layout/layoutMenu.cshtml";
}

<h2>Lista Servicios</h2>

<table border="1">
    <tr>
        <th>ID Servicio</th>
        <th>Descripción</th>
        <th>Monto</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID_Servicio</td>
            <td>@item.Descripcion</td>
            <td>@item.Monto</td>
            <td>@Html.ActionLink("Actualizar", "ModificarServicio", new { codigo = item.ID_Servicio })</td>
            <td>@Html.ActionLink("Eliminar", "EliminarServicio", new { codigo = item.ID_Servicio })</td>
        </tr>
    }
</table>

Presentacion/Views/Servicio/ModificarServicio.cshtml
@model Entidades.Servicios

@{
    ViewBag.Title = "ModificarServicio";
    Layout = "~/Views/layout/layoutMenu.cshtml";
}

<h2>Modificar Servicio</h2>

<div>
    @using (Html.BeginForm("ActualizarServicio", "Servicio", FormMethod.Post))
    {
    <div>
        <div>
            <label for="id">ID Servicio:</label>
            <input type="text" name="txtID" value="@Model.ID_Servicio" readonly/>
        </div>
        <div>
            <label for="descripcion">Descripción:</label>
            <input type="text" name="txtdescripcion" value="@Model.Descripcion"/>
        </div>
        <div>
            <label for="monto">Monto:</label>
            <input type="text" name="txtmonto" value="@Model.Monto"/>
        </div>
        <div>
            <button type="submit">Actualizar</button>
        </div>
    </div>
    }
</div>